### ISSUE TITLE
Update pod version

### ISSUE THREAD

**Issue by nickmshelley** [CrossWaterBridge/Swiftification#17]
Partly a reminder for me to do it later, partly hoping that someone else will first. 😄

**Comment by hiltonc** [comment]
Isn't it already updated?

**Comment by nickmshelley** [comment]
I did a pod update and it didn't come through, so I had to point to the commit. Maybe it needs to be push to the master specs repo or something?

**Comment by nickmshelley** [comment]
When I did point to the commit it said the version was higher tho.

**Comment by hiltonc** [comment]
```
$ pod trunk push

[!] Found podspec `Swiftification.podspec`
Updating spec repo `master`
Validating podspec
 -> Swiftification (5.3.2)

[!] Unable to accept duplicate entry for: Swiftification (5.3.2)
```

I did a pod update on LDSAnnotations this morning and it pulled the latest, maybe there's a caching issue on your computer?

**Comment by nickmshelley** [comment]
It's a brand new computer, I had to install cocoapods to even attempt a pod update. But maybe. :)

**Comment by nickmshelley** [comment]
We do have this in the podfile for some reason (probably copied and pasted from an old one somewhere): `source 'https://github.com/LDSChurch/LDSSpecs.git'`. Maybe that's causing problems.

**Comment by hiltonc** [comment]
```
$pod trunk push

[!] Found podspec `Swiftification.podspec`
Updating spec repo `master`
Validating podspec
 -> Swiftification (5.4.0)

Updating spec repo `master`
  - Data URL: https://raw.githubusercontent.com/CocoaPods/Specs/5000b86559090834d60ae48f941d53e79799e4d8/Specs/Swiftification/5.4.0/Swiftification.podspec.json
  - Log messages:
    - May 16th, 09:24: Push for `Swiftification 5.4.0' initiated.
    - May 16th, 09:24: Push for `Swiftification 5.4.0' has been pushed (2.975739349 s).
```
