### ISSUE TITLE
Make vars consistent.

### ISSUE THREAD

**Issue by nickmshelley** [CrossWaterBridge/Swiftification#19]
``` swift
var results: [Generator.Element] = []
var tempSet = Set<T>()
```

results should probably be

``` swift
var results = [Generator.Element]()
```

**Comment by hiltonc** [comment]
I tried, I get a compiler error:

<img width="768" alt="screen shot 2016-05-15 at 1 27 20 pm" src="https://cloud.githubusercontent.com/assets/470753/15276571/c898c66c-1aa0-11e6-8b17-40545e16e11e.png">

**Comment by nickmshelley** [comment]
Interesting, thanks for trying it.
