### ISSUE TITLE
Prep for Swift 3/iOS 10

### ISSUE THREAD

**Issue by SerenadeX** [CrossWaterBridge/Swiftification#34]
iOS 10 should be coming out in the next few weeks and Swift 3 with it.  This module should have some updates in it to reflect the changes that will happen in Swift 3

**Comment by nickmshelley** [comment]
@SerenadeX Pull requests welcome. :)

**Comment by SerenadeX** [comment]
Already been working on it.  Just thought I would document that I was on here.  I have almost finished it, I'm just running into a few problems with the `Dictionary.init` with a `<C: Collection>` generic.  Also `XCTAssertEqual` doesn't want to compare `Array`s and `Dictionary`s anymore

**Comment by hiltonc** [comment]
Thanks for getting this going.

**Comment by hiltonc** [comment]
Incidentally, there is a swift2.3 branch. When adding the swift3 branch, it'd be helpful if it branches from swift2.3. That seems to be a pattern that a lot of open source code is using.

**Comment by SerenadeX** [comment]
Oh rough cause I already started it, but I will see if I can rebase it from that branch

**Comment by SerenadeX** [comment]
Ok so I have all of the failures down but the `Dictionary.init`. I pushed up my branch `swift3`.  I need some help with this guy, its a doozy.  The pod will build fine, but it doesn't run tests because of an issue in the `DictionaryTests`.  Can anyone help take a look at it?

**Comment by hiltonc** [comment]
Replace that init with:

    init(elements: [(Key, Value)]) {
        self.init()
        for (key, value) in elements {
            self[key] = value
        }
    }

**Comment by SerenadeX** [comment]
Ok Xcode 8 GM has been released.  When do we want to update this to Swift 3?

**Comment by hiltonc** [comment]
I'm still using Swift 2.3 myself until I start using Swift 3 at work. I don't want to have to use both old and new syntax at once. I'm OK using the swift2.3 branch though if everyone else is ready to migrate master. Be sure to up the major version :).

**Comment by nickmshelley** [comment]
I'd personally prefer to wait until the official Xcode release. I don't plan on downloading Xcode 8 until then anyway.

**Comment by SerenadeX** [comment]
I have been trying to get Travis to build my `swift3` branch and pass the tests in #35 but I haven't had much success

**Comment by SerenadeX** [comment]
#35 is passing.  So what do you all want to do about it now? Is it something we want to merge in (and people can use 6.0.1 if they want Swift 2.3)?  What do you all think?

**Comment by hiltonc** [comment]
I'm still trying to get all my things onto Swift 2.3. I'm happy to explicitly use a `swift2.3` branch for that. If you want to make `master` be Swift 3, I don't have a problem with that.

**Comment by SerenadeX** [comment]
I think we should do that.  Then we can be ready to move to Swift 3 with this library when we move there with everything else.  I think the sooner we get things ready for Swift 3 the better
